name: Windows Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install OpenCL
      run: |
        vcpkg install opencl:x64-windows
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build . --config Release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: clpeak-windows
        path: build/Release/clpeak.exe
